/**
 * Embed an image as a data-URI constant for the wallpaper bundle.
 *
 * Usage: node scripts/embed-image.mjs <image-path> <out-path>
 * Example (package script): pnpm run embed
 *
 * Writes a TS module exporting `<BASENAME>_DATA_URI` with the image's
 * base64 data URI. Run it after replacing assets/asuka.jpg, then rebuild
 * the bundle (`pnpm --filter @deepseek-ai/dsh-client-ui-wallpaper run bundle`).
 */
import { readFile, writeFile } from 'node:fs/promises'
import { basename, resolve } from 'node:path'

const MIME_BY_EXTENSION = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
}

const [imageArg, outArg] = process.argv.slice(2)
if (imageArg === undefined || outArg === undefined) {
  console.error('usage: node scripts/embed-image.mjs <image-path> <out-path>')
  process.exit(1)
}

const imagePath = resolve(imageArg)
const outPath = resolve(outArg)
const extension = basename(imagePath).match(/\.[a-z0-9]+$/i)?.[0].toLowerCase()
const mime = extension !== undefined ? MIME_BY_EXTENSION[extension] : undefined
if (mime === undefined) {
  console.error(`unsupported image extension: ${extension ?? '(none)'} (supported: ${Object.keys(MIME_BY_EXTENSION).join(', ')})`)
  process.exit(1)
}

const base64 = (await readFile(imagePath)).toString('base64')
const name = basename(imagePath).replace(/[^A-Za-z0-9]/g, '_').toUpperCase()
const content = [
  '/**',
  ' * GENERATED by scripts/embed-image.mjs — do not edit by hand.',
  ` * Source: ${basename(imagePath)} (${mime}, ${(base64.length * 3 / 4).toFixed(0)} bytes).`,
  ' * Regenerate with `pnpm run embed` after replacing the source image.',
  ' */',
  `export const ${name}_DATA_URI = 'data:${mime};base64,${base64}'`,
  '',
].join('\n')

await writeFile(outPath, content)
console.log(`embedded ${imagePath} -> ${outPath} (${(base64.length / 1024).toFixed(0)} KiB base64)`)
